name: Continuous Integration
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CI_HELPERS_PREFIX: ci-helpers

jobs:
  check-mergeability:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: check
      run: |
        bash $CI_HELPERS_PREFIX/scripts/github_flow/check_mergeability.sh

  markdown-lint:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: lint
      run: |
        npm install --global markdownlint-cli
        markdownlint --config $CI_HELPERS_PREFIX/configs/executable.yml *.md
